package:
    name: sourcextractor 
    version: {{ GIT_DESCRIBE_TAG }}

source:
    git_rev: develop
    git_url: https://github.com/astrorama/sourcextractorplusplus.git

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

test:
    commands:
        - $PREFIX/bin/sourcextractor++ --version

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - elements ==5.8
        - alexandria ==2.14.1
        - boost ==1.70
        - cfitsio
        - CCfits
        - python
        - pytest
        - wcslib
        - fftw >=3
        - levmar >=2.6
        - gsl >=2.2.1
        - ncurses
    run:
        - elements ==5.8
        - alexandria ==2.14.1
        - boost ==1.70
        - cfitsio
        - CCfits
        - python
        - astropy
        - wcslib
        - fftw >=3
        - levmar >=2.6
        - gsl >=2.2.1
        - ncurses

app:
    entry: sourcextractor_launch.sh
    icon: sourcextractor_64.png
    summary: The next generation Source Extractor
    description: The next generation Source Extractor

about:
    home: https://github.com/astrorama/sourcextractorplusplus
    license: LGPLv3+
    license_file: LICENSE
    summary: The next generation Source Extractor

