package:
    name: sourcextractor 
    version: "0.13"

source:
    git_rev: develop
    git_url: https://github.com/astrorama/sourcextractorplusplus.git
    patches:
      - alexandria_2.17.1.patch

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

test:
    commands:
        - $PREFIX/bin/sourcextractor++ --version

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - elements ==5.10
        - alexandria ==2.17.1
        - boost ==1.70
        - cfitsio >=3.470
        - CCfits >=2.5
        - python >=3.7
        - pytest >=5.0.0
        - wcslib >=7.3
        - fftw >=3
        - levmar >=2.6
        - gsl >=2.2.1
        - onnx >=1.5.0
        - ncurses ==6.1
        - readline ==7
    run:
        - boost ==1.70
        - {{ pin_compatible('CCfits') }}
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('astropy') }}
        - {{ pin_compatible('wcslib') }}
        - {{ pin_compatible('fftw') }}
        - {{ pin_compatible('ncurses') }}

app:
    entry: sourcextractor_launch.sh
    icon: sourcextractor_64.png
    summary: The next generation Source Extractor
    description: The next generation Source Extractor

about:
    home: https://github.com/astrorama/sourcextractorplusplus
    license: LGPLv3+
    license_file: LICENSE
    summary: The next generation Source Extractor

