package:
    name: sextractorxx 
    version: "0.1"

source:
    url: "https://bintray.com/astrorama/archives/download_file?file_path=sextractorxx-0.1.tar.gz"

build:
    number: 6

test:
    commands:
        - $PREFIX/bin/sextractor++ --version

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - elements ==5.6
        - alexandria ==2.10_p2
        - boost ==1.69
        - cfitsio
        - "CCfits[channel=astrorama]"
        - python
        - pytest
        - wcslib
        - fftw >=3
        - levmar >=2.5
        - ncurses
    run:
        - elements ==5.6
        - alexandria ==2.10_p2
        - boost ==1.69
        - cfitsio
        - "CCfits[channel=astrorama]"
        - python
        - astropy
        - wcslib
        - fftw >=3
        - levmar >=2.5
        - ncurses

app:
    entry: sextractorxx_launch.sh
    icon: sextractorxx_64.png
    summary: The next generation SExtractor
    description: The next generation SExtractor

about:
    home: https://github.com/astrorama/sextractorxx.git
    license: LGPL
    summary: The next generation SExtractor

