package:
    name: sourcextractor 
    version: "0.11"

source:
    git_rev: develop
    git_url: https://github.com/astrorama/sourcextractorplusplus.git

build:
    number: 1

test:
    commands:
        - $PREFIX/bin/sourcextractor++ --version

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - elements ==5.10
        - alexandria ==2.16
        - boost ==1.70
        - cfitsio
        - CCfits
        - python
        - pytest
        - wcslib
        - fftw >=3
        - levmar >=2.6
        - gsl >=2.2.1
        # Force a minimum common version between conda-forge and anaconda
        - "ncurses ==6.1 [channel=anaconda]"
        - "readline ==7  [channel=anaconda]"
    run:
        - boost ==1.70
        - {{ pin_compatible('CCfits') }}
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('astropy') }}
        - {{ pin_compatible('wcslib') }}
        - {{ pin_compatible('fftw') }}
        - {{ pin_compatible('ncurses') }}

app:
    entry: sourcextractor_launch.sh
    icon: sourcextractor_64.png
    summary: The next generation Source Extractor
    description: The next generation Source Extractor

about:
    home: https://github.com/astrorama/sourcextractorplusplus
    license: LGPLv3+
    license_file: LICENSE
    summary: The next generation Source Extractor

