{% set name = "SourceXtractor" %}
{% set version = "0.13" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_rev: develop
    git_url: https://github.com/astrorama/sourcextractorplusplus.git
    patches:
      - alexandria_2.17.1.patch

build:
    number: c{{ build_number }}

test:
    commands:
        - $PREFIX/bin/sourcextractor++ --version

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - python
        - boost
        - alexandria ==2.17.1
        - cfitsio >=3.470
        - CCfits >=2.5
        - wcslib >=7.3
        - fftw >=3
        - levmar >=2.6
        - gsl >=2.2.1
        - onnx >=1.5.0
        - ncurses ==6.2
        - readline ==8
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cfitsio') }}
        - {{ pin_compatible('CCfits') }}
        - {{ pin_compatible('wcslib') }}
        - {{ pin_compatible('fftw') }}
        - {{ pin_compatible('levmar') }}
        - {{ pin_compatible('gsl') }}
        - {{ pin_compatible('onnx') }}
        - {{ pin_compatible('ncurses') }}
        - astropy

app:
    entry: sourcextractor_launch.sh
    icon: sourcextractor_64.png
    summary: The next generation Source Extractor
    description: The next generation Source Extractor

about:
    home: https://github.com/astrorama/sourcextractorplusplus
    license: LGPLv3+
    license_file: LICENSE
    summary: The next generation Source Extractor

